### ISSUE TITLE
How to use socks5 proxy

### ISSUE THREAD

**Issue by qbot955** [forestwanglin/okx-v5-java#6]
Api have to bind an ip, I need to use proxy for debugging

**Comment by forestwanglin** [comment]
Which type do you use, websocket or rest API?

**Comment by qbot955** [comment]
both

Wang Lin ***@***.***>于2024年7月22日 周一19:28写道：

**Comment by forestwanglin** [comment]
You can initial http client via proxy as below.

Websocket:
```java
    private OkxWsApiService getOkxWsService() {
        Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 7890));
        OkHttpClient client = defaultClient(Duration.ofMillis(300000))
                .newBuilder()
                .proxy(proxy)
                .build();
        return new OkxWsApiService(client, true);
    }
```

Rest API:
```java
    private OkxApiService getOkxService() {
        String apiKey = System.getenv("API_KEY");
        String passphrase = System.getenv("PASSPHRASE");
        String secretKey = System.getenv("SECRET_KEY");
        Duration defaultTimeout = Duration.ofSeconds(30);
        boolean simulated = true;
        Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 7890));
        OkHttpClient client = defaultClient(apiKey, secretKey, passphrase, simulated, defaultTimeout)
                .newBuilder()
                .proxy(proxy)
                .build();
        return new OkxApiService(buildApi(apiKey, secretKey, passphrase, simulated, defaultTimeout), client, simulated);
    }
```

**Comment by qbot955** [comment]
> You can initial http client via proxy as below.
> 
> Websocket:
> 
> ```java
>     private OkxWsApiService getOkxWsService() {
>         Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 7890));
>         OkHttpClient client = defaultClient(Duration.ofMillis(300000))
>                 .newBuilder()
>                 .proxy(proxy)
>                 .build();
>         return new OkxWsApiService(client, true);
>     }
> ```
> 
> Rest API:
> 
> ```java
>     private OkxApiService getOkxService() {
>         String apiKey = System.getenv("API_KEY");
>         String passphrase = System.getenv("PASSPHRASE");
>         String secretKey = System.getenv("SECRET_KEY");
>         Duration defaultTimeout = Duration.ofSeconds(30);
>         boolean simulated = true;
>         Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 7890));
>         OkHttpClient client = defaultClient(apiKey, secretKey, passphrase, simulated, defaultTimeout)
>                 .newBuilder()
>                 .proxy(proxy)
>                 .build();
>         return new OkxApiService(buildApi(apiKey, secretKey, passphrase, simulated, defaultTimeout), client, simulated);
>     }
> ```

Thanks, it works
